### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by sauliuni** [trikanna/electron-angular-meteor-ionic-starter-kit#1]
System: OSX 10.11
1. Install missing packages:
   npm install electron-prebuilt --save-dev
   npm install electron-rebuild --save-dev 
2. Do rebuild:
   ./node_modules/.bin/electron-rebuild
3. Start: npm run setup

Getting following npm error:

```
On Windows:  false
darwin
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn meteor ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

Did i missed something?

**Comment by sauliuni** [comment]
Wrong checkout, sorry
